services:
  - type: web
    name: youtube-mirror
    env: static
    staticPublishPath: public
    headers:
      - path: /cubecast/*.js
        name: Content-Type
        value: application/javascript
